version: 2
updates:
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: weekly
      time: '04:00'
    versioning-strategy: lockfile-only
    groups:
      dependencies:
        update-types:
          - "minor"
          - "patch"
