language: python
dist: bionic
install:
  - pip install -r requirements.txt
script:
  - python -m unittest test_asserts
  - mypy asserts test_asserts.py
  - flake8 asserts test_asserts.py
  - python -m doctest asserts/__init__.py
jobs:
  include:
    - stage: test
      python: 3.6
      dist: trusty
    - stage: test
      python: 3.7
    - stage: test
      python: 3.8
    - stage: test
      python: 3.9-dev
