name: Test srittau/black

on: [push]

jobs:
    black:
        name: Python 3.11
        runs-on: ubuntu-latest
        continue-on-error: true
        steps:
            - uses: actions/checkout@v4
            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                python-version: "3.11"
            - name: Default black version
              uses: srittau/black@dev
              continue-on-error: true
            - name: "version: 24.2.0"
              uses: srittau/black@dev
              continue-on-error: true
              with:
                version: 24.2.0
            - name: "version: ~=24.2"
              uses: srittau/black@dev
              continue-on-error: true
              with:
                use_pyproject: false
                version: ~=24.2
            - name: use_pyproject
              uses: srittau/black@dev
              continue-on-error: true
              with:
                use_pyproject: true
            - name: version and use_pyproject
              uses: srittau/black@dev
              continue-on-error: true
              with:
                use_pyproject: true
                version: 24.2.0
        
    old-python:
        name: Python 3.10
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                python-version: "3.10"
            - name: "version: 24.2.0"
              uses: srittau/black@dev
              continue-on-error: true
              with:
                version: 24.2.0
            - name: use_pyproject
              uses: srittau/black@dev
              continue-on-error: true
              with:
                use_pyproject: true
