name: Test srittau/black

on: [push]

jobs:
    black:
        runs-on: ubuntu-latest
        continue-on-error: true
        steps:
            - uses: actions/checkout@v4
            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                python-version: "3.11"
            - name: Default black version
              uses: srittau/black@dev
              continue-on-error: true
            - name: Hardcode fixed version
              uses: srittau/black@dev
              continue-on-error: true
              with:
                version: 24.2.0
            - name: Hardcode pattern
              uses: srittau/black@dev
              continue-on-error: true
              with:
                use_pyproject: false
                version: ~=24.*
            - name: Use pyproject.toml (true)
              uses: srittau/black@dev
              continue-on-error: true
              with:
                use_pyproject: true
            - name: Use pyproject.toml (on)
              uses: srittau/black@dev
              continue-on-error: true
              with:
                use_pyproject: on
            - name: Use both
              uses: srittau/black@dev
              continue-on-error: true
              with:
                use_pyproject: true
                version: 24.2.0
        
    old-python:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                python-version: "3.10"
            - name: Hardcode fixed version
              uses: srittau/black@dev
              continue-on-error: true
              with:
                version: 24.2.0
            - name: Use pyproject.toml
              uses: srittau/black@dev
              continue-on-error: true
              with:
                use_pyproject: true
